import { Router, Response } from 'express';
import { protectRoute, AuthRequest } from '../middlewares/authMiddleware';
import crypto from 'crypto';

const router = Router();

router.post('/', protectRoute, async (req: AuthRequest, res: Response): Promise<void> => {
    try {
        const userId = req.user?.id;
        
        const roomId = crypto.randomBytes(4).toString('hex');

        console.log(`[MeetAI] Room ${roomId} generated by User ID: ${userId}`);

        res.status(201).json({ 
            message: "Meeting created successfully",
            roomId: roomId 
        });

    } catch (error) {
        console.error("Meeting creation error:", error);
        res.status(500).json({ error: "Failed to create meeting." });
    }
});

export default router;